### ISSUE TITLE
💡 : Pin to dock on context menu

### ISSUE THREAD

**Issue by joe733** [cutefishos/launcher#10]
Hi it'd be good to have a `Pin to dock` and `Unpin from dock` on the right context menu from launcher.

**Comment by prateekmedia** [comment]
There's already `Send to dock` and `Remove from dock` in cutefish 0.5

**Comment by joe733** [comment]
Well I think the [`cutefish group`](https://archlinux.org/groups/x86_64/cutefish/) requires an update:

![image](https://user-images.githubusercontent.com/38415384/139835328-d2f957dd-4983-4ab3-bc70-5d7588ba826f.png)

**Comment by prateekmedia** [comment]
@joe733 Yes, below are some forum posts which talk the same:
- https://forum.cutefishos.com/d/190-update-packages-to-cutefish-05-for-arch-manjaro
- https://forum.cutefishos.com/d/133-cutefishos-05-beta-released/30
- https://forum.cutefishos.com/d/152-cutefish-05-on-arch-linux

For the time being you can build packages from AUR.
